# This file stores various settings for your site.
# You can include the values of these fields in markdown, e.g.:
# {{ site.data.settings.name }}

# The main name of your site
name: "CluedUp"

# A tagline for your site, often shown with the name
tagline: "The life-long learning conference"

# A description of your site, e.g. for social-media snippets
description: >
  CluedUp is South Africa’s first conference dedicated to lifelong learning and talent innovation.
  14–15 May 2019. W17 Watershed, Cape Town.

# The main language of your site. Use the IANA language subtag.
# See https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
# or lookup here: https://r12a.github.io/app-subtags/
language: "en"

# A default image for your site, e.g. for social-media snippets
image: "avatar.png"

# The logo for your site, if you have one
logo: "logo.svg"

# The final, canonical address of your live site
url: "http://cluedupconference.com"

# Your Google Analytics ID, if you're using Google Analytics
google-analytics-id: "UA-144363777-1"

# Your email address, e.g. for the contact form to use
email: "info@cluedupconference.com"
